// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWi-Y2FLzvKG4C3TuM_AcodmyIl0B6Q80',
    appId: '1:597117821678:web:0895e1bc4bd1e07b9689ff',
    messagingSenderId: '597117821678',
    projectId: 'rxdigi',
    authDomain: 'rxdigi.firebaseapp.com',
    storageBucket: 'rxdigi.firebasestorage.app',
    measurementId: 'G-QB6VTT0ZMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtv9FYEblO1ZSLONVIrq_b1jMqtHPaz2g',
    appId: '1:597117821678:android:ccb5333d69fba0cb9689ff',
    messagingSenderId: '597117821678',
    projectId: 'rxdigi',
    storageBucket: 'rxdigi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO4M-xaSy77XAfQ0_XZX8LeDEAObzrX0U',
    appId: '1:597117821678:ios:2d92d595be8dc2da9689ff',
    messagingSenderId: '597117821678',
    projectId: 'rxdigi',
    storageBucket: 'rxdigi.firebasestorage.app',
    iosBundleId: 'com.example.rxdigi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO4M-xaSy77XAfQ0_XZX8LeDEAObzrX0U',
    appId: '1:597117821678:ios:2d92d595be8dc2da9689ff',
    messagingSenderId: '597117821678',
    projectId: 'rxdigi',
    storageBucket: 'rxdigi.firebasestorage.app',
    iosBundleId: 'com.example.rxdigi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWi-Y2FLzvKG4C3TuM_AcodmyIl0B6Q80',
    appId: '1:597117821678:web:0301797a8be97b739689ff',
    messagingSenderId: '597117821678',
    projectId: 'rxdigi',
    authDomain: 'rxdigi.firebaseapp.com',
    storageBucket: 'rxdigi.firebasestorage.app',
    measurementId: 'G-VHC33B01ER',
  );
}
